### ISSUE TITLE
Make a tutorial on how to create themes

### ISSUE THREAD

**Issue by Sudobeast** [Beastslash/roblox-dialogue-maker#14]
They're pretty easy to make, but I gotta explain how to do it lol

**Comment by DraconicChris** [comment]
> "you can add also name to the npc at the top center of the dialog frame" https://devforum.roblox.com/t/dialogue-maker-plugin-beta/537321/8?u=draconicchris

**Comment by DraconicChris** [comment]
Maybe make a feature within the plugin to make themes

**Comment by joshuajon** [comment]
I would also like to see this tutorial :)

**Comment by Sudobeast** [comment]
devforum's down

**Comment by Sudobeast** [comment]
https://devforum.roblox.com/t/how-to-create-a-theme-for-dialogue-maker/1459334/1
