### ISSUE TITLE
Fix bug in SpeechBubbles

### ISSUE THREAD

**Issue by joshuajon** [Beastslash/roblox-dialogue-maker#41]
The SpeechBubble offset is broken due to an incorrect property name in ClientAPI script. Line 63 reads 

`SpeechBubbles[npc].StudsOffset = properties.StudsOffset`

but the property name in the Settings script on line 21 is SpeechBubbleStudsOffset

`SpeechBubbleStudsOffset = Vector3.new(0,4,0); -- Replace this with how far you want the speech bubble to be from the NPC's head. Measured in studs. [accepts Vector3]`

This causes the the ClientAPI to throw an error "expects Vector3, got nil" or similar.  Changing the reference to the correct property in ClientAPI fixes this problem:

`SpeechBubbles[npc].StudsOffset = properties.SpeechBubbleStudsOffset`

**Comment by Sudobeast** [comment]
Thank you! I'll check this out when I get home.
