### ISSUE TITLE
"PromptRegion.Part" should be "PromptRegion.BasePart"

### ISSUE THREAD

**Issue by DavidColetta** [Beastslash/roblox-dialogue-maker#86]
PromptRegion should automatically trigger dialog when I intersect a part of my choice. In the settings, it looks like this: 
```lua
PromptRegion = {
  Enabled = true; -- Do you want the conversation to automatically start when the player touches a part? [accepts boolean]
  BasePart = workspace.PromptPart; -- Change this value to a part. (Ex. workspace.Part) [accepts BasePart (i.e. Part, MeshPart, etc.) or nil]
};
```

This is all fine, except in DialogClientScript, the prompt region part is fetched using this line of code on line 36: 
`local PromptRegionPart = DialogueSettings.PromptRegion.Part;`

As you can see, in one place it is called 'basepart' and in another place it's called 'part'. I assume this is a typo, since most of the other parts are called basepart. This issue persists even when I press Fix Scripts. I modified the code myself to fix this, although if I ever press Fix Scripts I have to redo the fix.

```[tasklist]
### Completion criteria for developers
- [x] Replace all references of `DialogueSettings.PromptRegion.Part` with `dialogueSettings.promptRegion.BasePart`
- [x] Add DavidColetta to the Acknowledgments list
```

**Comment by Sudobeast** [comment]
This will be fixed in v5.0.0. Thanks!
