### ISSUE TITLE
Fix crash when attempting to skip dialogue

### ISSUE THREAD

**Issue by kitifulnines** [Beastslash/roblox-dialogue-maker#88]
If I press the continue key- say F for example- while the dialogue is still going, it crashes Roblox entirely. Not just in Studio, but on the actual platform as well.
When I click the GUI it works fine. It's the buttons that are causing problems.
I made a brand new project in Studio and attempted it without changing a _single_ thing within the settings and code- it still crashed.
![ezgif-5-4548fd0cd3](https://github.com/Beastslash/roblox-dialogue-maker/assets/131561323/7d938ef3-6cd4-4edd-b7a7-122fdce8cae0)

```[tasklist]
### Completion criteria for developers
- [x] Add kitfulnines to the Acknowledgements list
```

**Comment by Sudobeast** [comment]
Thanks for reporting this.

**Comment by Christian-Toney** [comment]
Unintentionally fixed the bug when developing text effects lol.

Not really sure what caused the problem.

**Comment by Christian-Toney** [comment]
I'll close #80 when I publish the fix
